#cloud-config
package_update: true
package_upgrade: true

runcmd:
  # install required packages
  - apt install -y docker.io
  - apt install -y docker-compose
  # - apt install -y unzip

  # - echo "[CUSTOM] Pulling down aws cli"
  # - curl -o "awscliv2.zip" "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
  # - unzip awscliv2.zip
  # - ./aws/install
  # - rm -rf awscliv2.zip
  # - rm -rf aws

  - cd /opt
  - git clone https://github.com/chang432/ai_bookclub.git
  - mv ai_bookclub/docker ./
  - rm -rf ai_bookclub

  - reboot

  - sleep 60
  - chmod +x /opt/docker/start_cloud.sh
  - chmod +x /opt/docker/start_cloud_helper.sh
  - /opt/docker/start_cloud.sh
  # - chmod +x /opt/docker/update.sh
  # - (crontab -l; echo "* 16 * * * /opt/docker/update.sh >> /var/log/update.log 2>&1") | crontab -     # 12 AM daily
  